#!/bin/bash
set -euo pipefail

# ============================================================================
# Docker Build Script for PyTorch Training Image
# ============================================================================
# Environment variables (all optional):
#   AWS_ACCOUNT_ID  - AWS account ID (default: auto-detect from AWS CLI)
#   AWS_REGION      - AWS region (default: us-west-2)
#   IMAGE_NAME      - Image name (default: pytorch-training)
#   IMAGE_TAG       - Image tag (default: latest)
#   PLATFORM        - Target platform (default: linux/amd64)
#
# Usage:
#   ./build.sh              # Build locally
#   ./build.sh --push       # Build and push to ECR
#   ./build.sh --tag v1.0   # Build with specific tag
#   ./build.sh --dev        # Build development target
# ============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Configurable variables
IMAGE_NAME="${IMAGE_NAME:-pytorch-training}"
IMAGE_TAG="${IMAGE_TAG:-latest}"
AWS_REGION="${AWS_REGION:-us-west-2}"
PLATFORM="${PLATFORM:-linux/amd64}"

# Parse arguments
TARGET="runtime"
PUSH=false
NO_CACHE=""

while [[ $# -gt 0 ]]; do
    case $1 in
        --dev)
            TARGET="development"
            shift
            ;;
        --push)
            PUSH=true
            shift
            ;;
        --no-cache)
            NO_CACHE="--no-cache"
            shift
            ;;
        --tag)
            IMAGE_TAG="$2"
            shift 2
            ;;
        --platform)
            PLATFORM="$2"
            shift 2
            ;;
        -h|--help)
            echo "Usage: $0 [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  --push          Push to ECR after building"
            echo "  --tag TAG       Set image tag (default: latest)"
            echo "  --platform PLAT Target platform (default: linux/amd64)"
            echo "  --dev           Build development target"
            echo ""
            echo "Environment variables:"
            echo "  AWS_ACCOUNT_ID  AWS account ID (auto-detected if not set)"
            echo "  AWS_REGION      AWS region (default: us-west-2)"
            echo "  IMAGE_NAME      Image name (default: pytorch-training)"
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            echo "Run '$0 --help' for usage"
            exit 1
            ;;
    esac
done

echo "Building Docker image..."
echo "  Image: ${IMAGE_NAME}:${IMAGE_TAG}"
echo "  Target: ${TARGET}"
echo "  Platform: ${PLATFORM}"

if [ "$PUSH" = true ]; then
    # Get AWS account ID for ECR push
    AWS_ACCOUNT_ID="${AWS_ACCOUNT_ID:-$(aws sts get-caller-identity --query Account --output text)}"
    ECR_REGISTRY="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
    FULL_IMAGE="${ECR_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}"

    echo "  ECR: ${FULL_IMAGE}"

    # Create ECR repository if it doesn't exist
    aws ecr describe-repositories --repository-names "${IMAGE_NAME}" --region "${AWS_REGION}" --no-cli-pager >/dev/null 2>&1 || \
        aws ecr create-repository --repository-name "${IMAGE_NAME}" --region "${AWS_REGION}" --no-cli-pager >/dev/null

    # Login to ECR
    aws ecr get-login-password --region "${AWS_REGION}" | \
        docker login --username AWS --password-stdin "${ECR_REGISTRY}"

    # Build and push with buildx (handles cross-platform)
    docker buildx build \
        --platform "${PLATFORM}" \
        --target "${TARGET}" \
        --tag "${FULL_IMAGE}" \
        --file "${SCRIPT_DIR}/Dockerfile" \
        ${NO_CACHE} \
        --push \
        "${PROJECT_ROOT}"

    echo ""
    echo "============================================================================"
    echo "Image pushed: ${FULL_IMAGE}"
    echo "============================================================================"

    # Auto-generate the image component kustomization
    IMAGE_KUSTOMIZATION="${PROJECT_ROOT}/kubernetes/components/image/kustomization.yaml"
    cat > "$IMAGE_KUSTOMIZATION" << EOF
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# Container image configuration (auto-generated by build.sh --push)
# DO NOT commit this file - it is gitignored

images:
  - name: pytorch-training
    newName: ${ECR_REGISTRY}/${IMAGE_NAME}
    newTag: ${IMAGE_TAG}
EOF
    echo "Generated: ${IMAGE_KUSTOMIZATION}"
else
    # Local build only
    docker buildx build \
        --platform "${PLATFORM}" \
        --target "${TARGET}" \
        --tag "${IMAGE_NAME}:${IMAGE_TAG}" \
        --file "${SCRIPT_DIR}/Dockerfile" \
        ${NO_CACHE} \
        --load \
        "${PROJECT_ROOT}"

    echo ""
    echo "Build completed: ${IMAGE_NAME}:${IMAGE_TAG}"
    echo "Run with --push to push to ECR"
fi
