apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ml-training

configurations:
  - kustomizeconfig.yaml

resources:
  - s3-config.yaml
  - rayjob.yaml

commonLabels:
  app.kubernetes.io/part-of: fine-tuning-on-eks
  app.kubernetes.io/component: ray-training
