apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ml-training

resources:
  - namespace.yaml
  - storage-class.yaml
  - training-job.yaml

commonLabels:
  app.kubernetes.io/part-of: fine-tuning-on-eks
